### ISSUE TITLE
Offer to take over the plugin

### ISSUE THREAD

**Issue by pluma** [peterjuras/vsc-fontsize-shortcuts#11]
I've created a fork at https://github.com/foss-haas/vsc-fontsize-shortcuts that implements a clean separation between handling editor and terminal font size with full backwards compatibility for people who want to keep the existing behaviour.

I'd like to take over as maintainer because I use the plugin myself and have recommended it to colleagues.

If your situation has changed and you no longer look for a new maintainer, I could also turn my fork into a PR instead.

**Comment by peterjuras** [comment]
Hi, thanks for offering to take over this extension.

I'd suggest you to publish the extensions yourself under a new/your publisher account. Afterwards we can create a deprecation message in this extension that suggests moving over to your extension. Is this ok for you?

**Comment by pluma** [comment]
Sure. Are you okay with keeping the configuration/shortcut names? This would make migration easier for existing users by maintaining backwards compatibility.

**Comment by pluma** [comment]
I've published `fosshaas.fontsize-shortcuts@1.4.0`.

**Comment by peterjuras** [comment]
Thanks a lot for publishing the new extension. My published extension has been updated with a deprecation warning and a link to your new extension.
