### ISSUE TITLE
Font size change seems sluggish

### ISSUE THREAD

**Issue by isometriq** [peterjuras/vsc-fontsize-shortcuts#3]
There seem to be delay when using the keyboard shortcuts, I would expect changer to be snappier. Maybe it's not relevant (extension limitation) ?

**Comment by peterjuras** [comment]
Hi!

How much delay are you experiencing when changing the font size with a shortcut? Due to extension API limitations, this extension currently modifies the user settings with the font size change. Therefore the editor reloads the user settings and adjusts the displayed font size accordingly.

**Comment by isometriq** [comment]
The font size is applied right then if I keep pressing, there is a 0.5~1 sec delay between changes. Since the increments are very small, it takes a while (5 sec) to get a decent size change). However, I just noticed the "fontshorcut.step" setting that may help reduce the problem.

**Comment by peterjuras** [comment]
Ok, I don't think there is a quicker way to do this with the current version of the extension API right now :/ I actually hope that the font size shortcuts get integrated into VSCode one day, so that this extension is not needed any longer.
