### ISSUE TITLE
CTRL+Mousewheel ?

### ISSUE THREAD

**Issue by isometriq** [peterjuras/vsc-fontsize-shortcuts#4]
Is that possible to also to implement the CTRL+Mousewheel like other IDE ?
I don't know if extension limitation would allow it.

**Comment by peterjuras** [comment]
Yes it is possible, even without this extension.
You have to set `"editor.mouseWheelZoom": true` in your user settings.

However there seems to be no easy way to reset or persist these zoom levels and the font size setting in the user settings are overridden by the mouse zoom levels.

**Comment by isometriq** [comment]
Nice! it works well thanks for the tip
