### ISSUE TITLE
Simultaneous change of terminal font.

### ISSUE THREAD

**Issue by cwunstel** [peterjuras/vsc-fontsize-shortcuts#5]
First, thanks for all of your work. I just installed the extension and everything works wonderfully. I noticed that the terminal size changes with the editor font size and that you implemented that change at 1.2.0. Any chance of making that option switchable? I'd like to be able to change only the editor font size. Much appreciated.

**Comment by peterjuras** [comment]
Hi,

sadly I have to tell you that I can't work on this project anymore and I'm on the search for a new maintainer for this extension. Until then, this issue will likely remain unsovled.

**Comment by cwunstel** [comment]
Thanks for your contribution.

**Comment by peterjuras** [comment]
This extension has been taken over by a new maintainer, please reopen your issue under the [new repository.](https://github.com/foss-haas/vsc-fontsize-shortcuts)
