### ISSUE TITLE
Getting the extension to work requires manual modification of keybindings

### ISSUE THREAD

**Issue by NeekSandhu** [peterjuras/vsc-fontsize-shortcuts#7]
Not sure if I did something wrong, but I had to modify my `keybindings.json` to get the extension to work. I'm sharing here for others who are having same issue (maybe add to readme)

```
[
    ...existing keybindings
    {
        "key": "ctrl+numpad_add",
        "command": "fontshortcuts.increaseFontSize"
    },
    {
        "key": "ctrl+numpad_subtract",
        "command": "fontshortcuts.decreaseFontSize"
    },
    {
        "key": "ctrl+numpad0",
        "command": "fontshortcuts.resetFontSize"
    }
]
```

**Comment by peterjuras** [comment]
Hi,

sadly I have to tell you that I can't work on this project anymore and I'm on the search for a new maintainer for this extension. Until then, this issue will likely remain unsolved.

**Comment by pluma** [comment]
The default bindings assume a layout like US QWERTY where the plus and minus keys are in those specific positions. I'm on QWERTZ and had to rebind as well. That's a limitation of how VSCode bindings work, so the plugin can't really do anything about that.

**Comment by peterjuras** [comment]
This extension has been taken over by a new maintainer, please reopen your issue under the [new repository.](https://github.com/foss-haas/vsc-fontsize-shortcuts)
