### ISSUE TITLE
Feature Request: Add option to separately change editor and interactive terminal font size

### ISSUE THREAD

**Issue by choushishi** [peterjuras/vsc-fontsize-shortcuts#8]
As the title suggests, it would be nice if we can have the option to change only the editor/terminal font size. Most of the time I would like to have smaller font in the terminal so I have to manually change it in the preference after I changed the editor to the desired font size.

**Comment by peterjuras** [comment]
Hi,

sadly I have to tell you that I can't work on this project anymore and I'm on the search for a new maintainer for this extension. Until then, this issue will likely remain unsolved.

**Comment by pluma** [comment]
This is effectively a duplicate of #5.

**Comment by peterjuras** [comment]
This extension has been taken over by a new maintainer, please reopen your issue under the [new repository.](https://github.com/foss-haas/vsc-fontsize-shortcuts)
